### ISSUE TITLE
Feature Request: Custom Background

### ISSUE THREAD

**Issue by avamsi** [vhanla/SublimeTextTrans#18]
Can you please add an option to provide an image which will be used as Sublime's background instead of the application that's behind it?

Something like this - [ConEmu | Settings: Background](https://conemu.github.io/en/SettingsBackground)

**Comment by vhanla** [comment]
As of now, I don't know a feasable method to achieve that since this plugin only modifies the window's opacity using WinAPI. It could be modified by another program by updating the layered window, but I guess it would completely make the IDE unresponsive, unless the SublimeText itself allows it, I don't know any other method to achieve that. Sorry.

**Comment by avamsi** [comment]
@vhanla No worries! Thanks for a great plugin! :)
