### ISSUE TITLE
doesn't work on macox

### ISSUE THREAD

**Issue by drduan** [vhanla/SublimeTextTrans#21]
<img width="772" alt="2017-01-17 11 08 36" src="https://cloud.githubusercontent.com/assets/7875572/22025845/f742491c-dd09-11e6-8f92-587ec23649c8.png">

Like this~

**Comment by Sergey6116** [comment]
+1

**Comment by vhanla** [comment]
Sorry, this only supports Window's APIs to handle windows transparency, since Sublime Text uses its own window manager for unix/linux OSes, so I can't make it transparent on those operating systems, and sublime programmers are not going to implement that feature AFAIK, at least in the near future. 

Maybe you should try Afloat
