### ISSUE TITLE
No settings menu in Sublime Text 3

### ISSUE THREAD

**Issue by zachsa** [vhanla/SublimeTextTrans#24]
I wanted to adjust the transparency levels, which according to the readme can be done via: `Preferences > Package Settings > SublimeTextTrans > Settings - User`

But this menu doesn't exist on Sublime Text 3. Otherwise thanks for a great plugin!

**Comment by nakami** [comment]
did you adjust the git clone command according to ST3 instead of ST2?

so instead of...
`git clone https://github.com/vhanla/SublimeTextTrans.git "%APPDATA%\Sublime Text 2\Packages\SublimeTextTrans"`
use:
`git clone https://github.com/vhanla/SublimeTextTrans.git "%APPDATA%\Sublime Text 3\Packages\SublimeTextTrans"`

**Comment by zachsa** [comment]
I can't remember ... I think I just used the built-in package installer? I do have the menu item `Preferences > Opacity`, but that doesn't have transparency levels.

I think (but my memory could be fault) that I adjusted the transparency levels in a settings file direclty

**Comment by jackjianguo** [comment]
copy this repo to C:\Users\yourname\AppData\Roaming\Sublime Text 3\Packages\, then sublime text 3 Preferences->Opactity is ok.

**Comment by vhanla** [comment]
Sorry, to answer late, the package installer is using a fork somebody else did. I sent a pull request to Sublime Text package, hopefully they will accept it.
