### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by shmolf** [vhanla/SublimeTextTrans#33]
Enabling the plugin triggers a Trojan alert from McAfee.
Matches RDN/Generic.hbg

**Comment by mdanlowski** [comment]
Same.
Any ideas why?

**Comment by vhanla** [comment]
This issue was long discussed. /lib/SetSublimeLayere.asm creates a small binary (1KB) that will change SublimeText's Window Ex Style mode to LayeredWindow. Trying to change from within a child python script crashes Sublime, that's why an external application is needed.

Some antiviruses detect it as dangerous. I don't know why, but it is a false positive. You can compile it by yourself using FlatAssembler.
